// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfqEJ93jDmoayfhXvhxfxJGy-BnKkUYI',
    appId: '1:270692063572:web:d04e33c8f86d8b2e76d0c1',
    messagingSenderId: '270692063572',
    projectId: 'quote-b17bf',
    authDomain: 'quote-b17bf.firebaseapp.com',
    storageBucket: 'quote-b17bf.appspot.com',
    measurementId: 'G-YBS3GY272G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDLwst2BzUDYJ0VS-R6wG7Nt80skZQXc4',
    appId: '1:270692063572:android:1e286fc4b61d73ab76d0c1',
    messagingSenderId: '270692063572',
    projectId: 'quote-b17bf',
    storageBucket: 'quote-b17bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdYJnI-Q07A9i2FazdhcPXhUWoYSUC0k',
    appId: '1:270692063572:ios:0bc75e98e958aeb576d0c1',
    messagingSenderId: '270692063572',
    projectId: 'quote-b17bf',
    storageBucket: 'quote-b17bf.appspot.com',
    iosBundleId: 'com.example.qouteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdYJnI-Q07A9i2FazdhcPXhUWoYSUC0k',
    appId: '1:270692063572:ios:185054f78c03ab4476d0c1',
    messagingSenderId: '270692063572',
    projectId: 'quote-b17bf',
    storageBucket: 'quote-b17bf.appspot.com',
    iosBundleId: 'com.example.qouteapp.RunnerTests',
  );
}
